site_name: Munich Imputation Server
theme: readthedocs

nav:
- Home: index.md
- Genotype Imputation:
  - Getting Started: getting-started.md
  - Data Preparation: prepare-your-data.md
  - Reference Panels: reference-panels.md
  - Pipeline Overview: pipeline.md
  - Security: data-sensitivity.md
  - FAQ: faq.md
- Polygenic Score Calculation:
    - Getting Started: pgs/getting-started.md
    - Step-by-Step Tutorial: pgs/tutorial.md
    - Interactive Report: pgs/report.md
    - Output Files: pgs/output-files.md
    - Reference Panels: pgs/reference-panels.md
    - Available Scores: pgs/scores.md
    - Pipeline Overview: pgs/pipeline.md
    - FAQ: pgs/faq.md
- Developer Documentation:
  - API: api.md
  - Docker: docker.md
  - Create Reference Panels: create-reference-panels.md
- Contact: contact.md

repo_name: hmgu-itg/imputationserver
repo_url: https://github.com/hmgu-itg/imputationserver
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt
      link: https://github.com/hmgu-itg/imputationserver

markdown_extensions:
    - toc:
        permalink:
    - admonition:
